package com.test.springboot.shiro.dao.entity;

import java.util.Date;

public class AlarmHistoralEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_alarm_historal.id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_alarm_historal.create_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_alarm_historal.last_modify_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Date lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_alarm_historal.device_id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Integer deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_alarm_historal.definition_id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Integer definitionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_alarm_historal.notify_status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Byte notifyStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_alarm_historal.device_name
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private String deviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_alarm_historal.workshop_name
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private String workshopName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_alarm_historal.product_line_name
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private String productLineName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_alarm_historal.id
     *
     * @return the value of tb_alarm_historal.id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_alarm_historal.id
     *
     * @param id the value for tb_alarm_historal.id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_alarm_historal.create_time
     *
     * @return the value of tb_alarm_historal.create_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_alarm_historal.create_time
     *
     * @param createTime the value for tb_alarm_historal.create_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_alarm_historal.last_modify_time
     *
     * @return the value of tb_alarm_historal.last_modify_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_alarm_historal.last_modify_time
     *
     * @param lastModifyTime the value for tb_alarm_historal.last_modify_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_alarm_historal.device_id
     *
     * @return the value of tb_alarm_historal.device_id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_alarm_historal.device_id
     *
     * @param deviceId the value for tb_alarm_historal.device_id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_alarm_historal.definition_id
     *
     * @return the value of tb_alarm_historal.definition_id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Integer getDefinitionId() {
        return definitionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_alarm_historal.definition_id
     *
     * @param definitionId the value for tb_alarm_historal.definition_id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setDefinitionId(Integer definitionId) {
        this.definitionId = definitionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_alarm_historal.notify_status
     *
     * @return the value of tb_alarm_historal.notify_status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Byte getNotifyStatus() {
        return notifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_alarm_historal.notify_status
     *
     * @param notifyStatus the value for tb_alarm_historal.notify_status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setNotifyStatus(Byte notifyStatus) {
        this.notifyStatus = notifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_alarm_historal.device_name
     *
     * @return the value of tb_alarm_historal.device_name
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_alarm_historal.device_name
     *
     * @param deviceName the value for tb_alarm_historal.device_name
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName == null ? null : deviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_alarm_historal.workshop_name
     *
     * @return the value of tb_alarm_historal.workshop_name
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public String getWorkshopName() {
        return workshopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_alarm_historal.workshop_name
     *
     * @param workshopName the value for tb_alarm_historal.workshop_name
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setWorkshopName(String workshopName) {
        this.workshopName = workshopName == null ? null : workshopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_alarm_historal.product_line_name
     *
     * @return the value of tb_alarm_historal.product_line_name
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public String getProductLineName() {
        return productLineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_alarm_historal.product_line_name
     *
     * @param productLineName the value for tb_alarm_historal.product_line_name
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setProductLineName(String productLineName) {
        this.productLineName = productLineName == null ? null : productLineName.trim();
    }
}