package com.test.springboot.shiro.dao.entity;

import java.util.Date;

public class AlarmDefinitionEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_alarm_definition.id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_alarm_definition.create_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_alarm_definition.last_modify_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Date lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_alarm_definition.alarm_name
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private String alarmName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_alarm_definition.alarm_content
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private String alarmContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_alarm_definition.alarm_level
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Byte alarmLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_alarm_definition.receiver_emails
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private String receiverEmails;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_alarm_definition.id
     *
     * @return the value of tb_alarm_definition.id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_alarm_definition.id
     *
     * @param id the value for tb_alarm_definition.id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_alarm_definition.create_time
     *
     * @return the value of tb_alarm_definition.create_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_alarm_definition.create_time
     *
     * @param createTime the value for tb_alarm_definition.create_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_alarm_definition.last_modify_time
     *
     * @return the value of tb_alarm_definition.last_modify_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_alarm_definition.last_modify_time
     *
     * @param lastModifyTime the value for tb_alarm_definition.last_modify_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_alarm_definition.alarm_name
     *
     * @return the value of tb_alarm_definition.alarm_name
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public String getAlarmName() {
        return alarmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_alarm_definition.alarm_name
     *
     * @param alarmName the value for tb_alarm_definition.alarm_name
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setAlarmName(String alarmName) {
        this.alarmName = alarmName == null ? null : alarmName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_alarm_definition.alarm_content
     *
     * @return the value of tb_alarm_definition.alarm_content
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public String getAlarmContent() {
        return alarmContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_alarm_definition.alarm_content
     *
     * @param alarmContent the value for tb_alarm_definition.alarm_content
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setAlarmContent(String alarmContent) {
        this.alarmContent = alarmContent == null ? null : alarmContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_alarm_definition.alarm_level
     *
     * @return the value of tb_alarm_definition.alarm_level
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Byte getAlarmLevel() {
        return alarmLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_alarm_definition.alarm_level
     *
     * @param alarmLevel the value for tb_alarm_definition.alarm_level
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setAlarmLevel(Byte alarmLevel) {
        this.alarmLevel = alarmLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_alarm_definition.receiver_emails
     *
     * @return the value of tb_alarm_definition.receiver_emails
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public String getReceiverEmails() {
        return receiverEmails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_alarm_definition.receiver_emails
     *
     * @param receiverEmails the value for tb_alarm_definition.receiver_emails
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setReceiverEmails(String receiverEmails) {
        this.receiverEmails = receiverEmails == null ? null : receiverEmails.trim();
    }
}