package com.test.springboot.shiro.dao.entity;

import java.util.Date;

public class GlobalSettingEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_global_setting.id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_global_setting.setting_key
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private String settingKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_global_setting.setting_value
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private String settingValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_global_setting.create_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_global_setting.last_modify_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Date lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_global_setting.status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_global_setting.id
     *
     * @return the value of tb_global_setting.id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_global_setting.id
     *
     * @param id the value for tb_global_setting.id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_global_setting.setting_key
     *
     * @return the value of tb_global_setting.setting_key
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public String getSettingKey() {
        return settingKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_global_setting.setting_key
     *
     * @param settingKey the value for tb_global_setting.setting_key
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setSettingKey(String settingKey) {
        this.settingKey = settingKey == null ? null : settingKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_global_setting.setting_value
     *
     * @return the value of tb_global_setting.setting_value
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public String getSettingValue() {
        return settingValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_global_setting.setting_value
     *
     * @param settingValue the value for tb_global_setting.setting_value
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setSettingValue(String settingValue) {
        this.settingValue = settingValue == null ? null : settingValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_global_setting.create_time
     *
     * @return the value of tb_global_setting.create_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_global_setting.create_time
     *
     * @param createTime the value for tb_global_setting.create_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_global_setting.last_modify_time
     *
     * @return the value of tb_global_setting.last_modify_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_global_setting.last_modify_time
     *
     * @param lastModifyTime the value for tb_global_setting.last_modify_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_global_setting.status
     *
     * @return the value of tb_global_setting.status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_global_setting.status
     *
     * @param status the value for tb_global_setting.status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}