package com.test.springboot.shiro.dao.entity;

import java.util.Date;

public class MalfunctionDefinitionEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_malfunction_definition.id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_malfunction_definition.create_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_malfunction_definition.last_modify_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Date lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_malfunction_definition.type
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_malfunction_definition.display_name
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private String displayName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_malfunction_definition.device_type
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private String deviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_malfunction_definition.desc_info
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private String descInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_malfunction_definition.id
     *
     * @return the value of tb_malfunction_definition.id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_malfunction_definition.id
     *
     * @param id the value for tb_malfunction_definition.id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_malfunction_definition.create_time
     *
     * @return the value of tb_malfunction_definition.create_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_malfunction_definition.create_time
     *
     * @param createTime the value for tb_malfunction_definition.create_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_malfunction_definition.last_modify_time
     *
     * @return the value of tb_malfunction_definition.last_modify_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_malfunction_definition.last_modify_time
     *
     * @param lastModifyTime the value for tb_malfunction_definition.last_modify_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_malfunction_definition.type
     *
     * @return the value of tb_malfunction_definition.type
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_malfunction_definition.type
     *
     * @param type the value for tb_malfunction_definition.type
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_malfunction_definition.display_name
     *
     * @return the value of tb_malfunction_definition.display_name
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_malfunction_definition.display_name
     *
     * @param displayName the value for tb_malfunction_definition.display_name
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName == null ? null : displayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_malfunction_definition.device_type
     *
     * @return the value of tb_malfunction_definition.device_type
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_malfunction_definition.device_type
     *
     * @param deviceType the value for tb_malfunction_definition.device_type
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType == null ? null : deviceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_malfunction_definition.desc_info
     *
     * @return the value of tb_malfunction_definition.desc_info
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public String getDescInfo() {
        return descInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_malfunction_definition.desc_info
     *
     * @param descInfo the value for tb_malfunction_definition.desc_info
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setDescInfo(String descInfo) {
        this.descInfo = descInfo == null ? null : descInfo.trim();
    }
}