package com.test.springboot.shiro.dao.entity;

import java.util.Date;

public class ResourceOperationEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_resource_operation.id
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_resource_operation.resource_type_view
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    private String resourceTypeView;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_resource_operation.resource_type
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    private String resourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_resource_operation.operation_type
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    private String operationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_resource_operation.permission
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_resource_operation.api_status
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    private Byte apiStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_resource_operation.create_time
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_resource_operation.last_modify_time
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    private Date lastModifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_resource_operation.id
     *
     * @return the value of tb_resource_operation.id
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_resource_operation.id
     *
     * @param id the value for tb_resource_operation.id
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_resource_operation.resource_type_view
     *
     * @return the value of tb_resource_operation.resource_type_view
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    public String getResourceTypeView() {
        return resourceTypeView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_resource_operation.resource_type_view
     *
     * @param resourceTypeView the value for tb_resource_operation.resource_type_view
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    public void setResourceTypeView(String resourceTypeView) {
        this.resourceTypeView = resourceTypeView == null ? null : resourceTypeView.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_resource_operation.resource_type
     *
     * @return the value of tb_resource_operation.resource_type
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_resource_operation.resource_type
     *
     * @param resourceType the value for tb_resource_operation.resource_type
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType == null ? null : resourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_resource_operation.operation_type
     *
     * @return the value of tb_resource_operation.operation_type
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_resource_operation.operation_type
     *
     * @param operationType the value for tb_resource_operation.operation_type
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    public void setOperationType(String operationType) {
        this.operationType = operationType == null ? null : operationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_resource_operation.permission
     *
     * @return the value of tb_resource_operation.permission
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_resource_operation.permission
     *
     * @param permission the value for tb_resource_operation.permission
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_resource_operation.api_status
     *
     * @return the value of tb_resource_operation.api_status
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    public Byte getApiStatus() {
        return apiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_resource_operation.api_status
     *
     * @param apiStatus the value for tb_resource_operation.api_status
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    public void setApiStatus(Byte apiStatus) {
        this.apiStatus = apiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_resource_operation.create_time
     *
     * @return the value of tb_resource_operation.create_time
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_resource_operation.create_time
     *
     * @param createTime the value for tb_resource_operation.create_time
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_resource_operation.last_modify_time
     *
     * @return the value of tb_resource_operation.last_modify_time
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_resource_operation.last_modify_time
     *
     * @param lastModifyTime the value for tb_resource_operation.last_modify_time
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }
}