package com.test.springboot.shiro.dao.entity;

import java.util.Date;

public class UserLogEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_log.id
     *
     * @mbggenerated Mon May 21 11:11:19 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_log.user_id
     *
     * @mbggenerated Mon May 21 11:11:19 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_log.create_time
     *
     * @mbggenerated Mon May 21 11:11:19 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_log.status
     *
     * @mbggenerated Mon May 21 11:11:19 CST 2018
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_log.ip
     *
     * @mbggenerated Mon May 21 11:11:19 CST 2018
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_log.content
     *
     * @mbggenerated Mon May 21 11:11:19 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_log.id
     *
     * @return the value of tb_user_log.id
     *
     * @mbggenerated Mon May 21 11:11:19 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_log.id
     *
     * @param id the value for tb_user_log.id
     *
     * @mbggenerated Mon May 21 11:11:19 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_log.user_id
     *
     * @return the value of tb_user_log.user_id
     *
     * @mbggenerated Mon May 21 11:11:19 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_log.user_id
     *
     * @param userId the value for tb_user_log.user_id
     *
     * @mbggenerated Mon May 21 11:11:19 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_log.create_time
     *
     * @return the value of tb_user_log.create_time
     *
     * @mbggenerated Mon May 21 11:11:19 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_log.create_time
     *
     * @param createTime the value for tb_user_log.create_time
     *
     * @mbggenerated Mon May 21 11:11:19 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_log.status
     *
     * @return the value of tb_user_log.status
     *
     * @mbggenerated Mon May 21 11:11:19 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_log.status
     *
     * @param status the value for tb_user_log.status
     *
     * @mbggenerated Mon May 21 11:11:19 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_log.ip
     *
     * @return the value of tb_user_log.ip
     *
     * @mbggenerated Mon May 21 11:11:19 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_log.ip
     *
     * @param ip the value for tb_user_log.ip
     *
     * @mbggenerated Mon May 21 11:11:19 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_log.content
     *
     * @return the value of tb_user_log.content
     *
     * @mbggenerated Mon May 21 11:11:19 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_log.content
     *
     * @param content the value for tb_user_log.content
     *
     * @mbggenerated Mon May 21 11:11:19 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}