package com.test.springboot.shiro.dao.entity;

import java.util.Date;

public class ViewMenuEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_view_menu.id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_view_menu.menu_name
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_view_menu.parent_menu_id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Integer parentMenuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_view_menu.menu_label
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private String menuLabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_view_menu.create_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_view_menu.last_modify_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Date lastModifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_view_menu.id
     *
     * @return the value of tb_view_menu.id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_view_menu.id
     *
     * @param id the value for tb_view_menu.id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_view_menu.menu_name
     *
     * @return the value of tb_view_menu.menu_name
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_view_menu.menu_name
     *
     * @param menuName the value for tb_view_menu.menu_name
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_view_menu.parent_menu_id
     *
     * @return the value of tb_view_menu.parent_menu_id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Integer getParentMenuId() {
        return parentMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_view_menu.parent_menu_id
     *
     * @param parentMenuId the value for tb_view_menu.parent_menu_id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setParentMenuId(Integer parentMenuId) {
        this.parentMenuId = parentMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_view_menu.menu_label
     *
     * @return the value of tb_view_menu.menu_label
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public String getMenuLabel() {
        return menuLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_view_menu.menu_label
     *
     * @param menuLabel the value for tb_view_menu.menu_label
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setMenuLabel(String menuLabel) {
        this.menuLabel = menuLabel == null ? null : menuLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_view_menu.create_time
     *
     * @return the value of tb_view_menu.create_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_view_menu.create_time
     *
     * @param createTime the value for tb_view_menu.create_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_view_menu.last_modify_time
     *
     * @return the value of tb_view_menu.last_modify_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_view_menu.last_modify_time
     *
     * @param lastModifyTime the value for tb_view_menu.last_modify_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }
}