package com.test.springboot.shiro.dao.entity;

import java.util.Date;

public class WorkshopEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_workshop.id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_workshop.create_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_workshop.last_modify_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Date lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_workshop.name
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_workshop.person_liable_id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Integer personLiableId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_workshop.desc_info
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private String descInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_workshop.id
     *
     * @return the value of tb_workshop.id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_workshop.id
     *
     * @param id the value for tb_workshop.id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_workshop.create_time
     *
     * @return the value of tb_workshop.create_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_workshop.create_time
     *
     * @param createTime the value for tb_workshop.create_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_workshop.last_modify_time
     *
     * @return the value of tb_workshop.last_modify_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_workshop.last_modify_time
     *
     * @param lastModifyTime the value for tb_workshop.last_modify_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_workshop.name
     *
     * @return the value of tb_workshop.name
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_workshop.name
     *
     * @param name the value for tb_workshop.name
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_workshop.person_liable_id
     *
     * @return the value of tb_workshop.person_liable_id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Integer getPersonLiableId() {
        return personLiableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_workshop.person_liable_id
     *
     * @param personLiableId the value for tb_workshop.person_liable_id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setPersonLiableId(Integer personLiableId) {
        this.personLiableId = personLiableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_workshop.desc_info
     *
     * @return the value of tb_workshop.desc_info
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public String getDescInfo() {
        return descInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_workshop.desc_info
     *
     * @param descInfo the value for tb_workshop.desc_info
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setDescInfo(String descInfo) {
        this.descInfo = descInfo == null ? null : descInfo.trim();
    }
}