package com.test.springboot.shiro.dao.entity;

import java.util.Date;

public class WorkStatusEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_work_status.id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_work_status.create_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_work_status.last_modify_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Date lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_work_status.target_level
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Byte targetLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_work_status.target_id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Integer targetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_work_status.monitor_key
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private String monitorKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_work_status.monitor_value
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Integer monitorValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_work_status.is_realtime
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Byte isRealtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_work_status.id
     *
     * @return the value of tb_work_status.id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_work_status.id
     *
     * @param id the value for tb_work_status.id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_work_status.create_time
     *
     * @return the value of tb_work_status.create_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_work_status.create_time
     *
     * @param createTime the value for tb_work_status.create_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_work_status.last_modify_time
     *
     * @return the value of tb_work_status.last_modify_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_work_status.last_modify_time
     *
     * @param lastModifyTime the value for tb_work_status.last_modify_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_work_status.target_level
     *
     * @return the value of tb_work_status.target_level
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Byte getTargetLevel() {
        return targetLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_work_status.target_level
     *
     * @param targetLevel the value for tb_work_status.target_level
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setTargetLevel(Byte targetLevel) {
        this.targetLevel = targetLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_work_status.target_id
     *
     * @return the value of tb_work_status.target_id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Integer getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_work_status.target_id
     *
     * @param targetId the value for tb_work_status.target_id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setTargetId(Integer targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_work_status.monitor_key
     *
     * @return the value of tb_work_status.monitor_key
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public String getMonitorKey() {
        return monitorKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_work_status.monitor_key
     *
     * @param monitorKey the value for tb_work_status.monitor_key
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setMonitorKey(String monitorKey) {
        this.monitorKey = monitorKey == null ? null : monitorKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_work_status.monitor_value
     *
     * @return the value of tb_work_status.monitor_value
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Integer getMonitorValue() {
        return monitorValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_work_status.monitor_value
     *
     * @param monitorValue the value for tb_work_status.monitor_value
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setMonitorValue(Integer monitorValue) {
        this.monitorValue = monitorValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_work_status.is_realtime
     *
     * @return the value of tb_work_status.is_realtime
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Byte getIsRealtime() {
        return isRealtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_work_status.is_realtime
     *
     * @param isRealtime the value for tb_work_status.is_realtime
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setIsRealtime(Byte isRealtime) {
        this.isRealtime = isRealtime;
    }
}