package com.test.springboot.shiro.dao.entity;

import java.util.Date;

public class WorkorderEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_workorder.id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_workorder.create_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_workorder.last_modify_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Date lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_workorder.device_id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Integer deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_workorder.desc_info
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private String descInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_workorder.create_user
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_workorder.person_liable
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private String personLiable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_workorder.malfunction_id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Integer malfunctionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_workorder.reviewer
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private String reviewer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_workorder.status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_workorder.owner
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private String owner;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_workorder.id
     *
     * @return the value of tb_workorder.id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_workorder.id
     *
     * @param id the value for tb_workorder.id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_workorder.create_time
     *
     * @return the value of tb_workorder.create_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_workorder.create_time
     *
     * @param createTime the value for tb_workorder.create_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_workorder.last_modify_time
     *
     * @return the value of tb_workorder.last_modify_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_workorder.last_modify_time
     *
     * @param lastModifyTime the value for tb_workorder.last_modify_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_workorder.device_id
     *
     * @return the value of tb_workorder.device_id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_workorder.device_id
     *
     * @param deviceId the value for tb_workorder.device_id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_workorder.desc_info
     *
     * @return the value of tb_workorder.desc_info
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public String getDescInfo() {
        return descInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_workorder.desc_info
     *
     * @param descInfo the value for tb_workorder.desc_info
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setDescInfo(String descInfo) {
        this.descInfo = descInfo == null ? null : descInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_workorder.create_user
     *
     * @return the value of tb_workorder.create_user
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_workorder.create_user
     *
     * @param createUser the value for tb_workorder.create_user
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_workorder.person_liable
     *
     * @return the value of tb_workorder.person_liable
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public String getPersonLiable() {
        return personLiable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_workorder.person_liable
     *
     * @param personLiable the value for tb_workorder.person_liable
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setPersonLiable(String personLiable) {
        this.personLiable = personLiable == null ? null : personLiable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_workorder.malfunction_id
     *
     * @return the value of tb_workorder.malfunction_id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Integer getMalfunctionId() {
        return malfunctionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_workorder.malfunction_id
     *
     * @param malfunctionId the value for tb_workorder.malfunction_id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setMalfunctionId(Integer malfunctionId) {
        this.malfunctionId = malfunctionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_workorder.reviewer
     *
     * @return the value of tb_workorder.reviewer
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public String getReviewer() {
        return reviewer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_workorder.reviewer
     *
     * @param reviewer the value for tb_workorder.reviewer
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setReviewer(String reviewer) {
        this.reviewer = reviewer == null ? null : reviewer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_workorder.status
     *
     * @return the value of tb_workorder.status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_workorder.status
     *
     * @param status the value for tb_workorder.status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_workorder.owner
     *
     * @return the value of tb_workorder.owner
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_workorder.owner
     *
     * @param owner the value for tb_workorder.owner
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }
}