package com.test.springboot.shiro.dao.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WorkStatusEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_work_status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_work_status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_work_status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_work_status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public WorkStatusEntityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_work_status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_work_status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_work_status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_work_status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_work_status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_work_status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_work_status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_work_status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_work_status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_work_status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_work_status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeIsNull() {
            addCriterion("last_modify_time is null");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeIsNotNull() {
            addCriterion("last_modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeEqualTo(Date value) {
            addCriterion("last_modify_time =", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeNotEqualTo(Date value) {
            addCriterion("last_modify_time <>", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeGreaterThan(Date value) {
            addCriterion("last_modify_time >", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_modify_time >=", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeLessThan(Date value) {
            addCriterion("last_modify_time <", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_modify_time <=", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeIn(List<Date> values) {
            addCriterion("last_modify_time in", values, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeNotIn(List<Date> values) {
            addCriterion("last_modify_time not in", values, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeBetween(Date value1, Date value2) {
            addCriterion("last_modify_time between", value1, value2, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_modify_time not between", value1, value2, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andTargetLevelIsNull() {
            addCriterion("target_level is null");
            return (Criteria) this;
        }

        public Criteria andTargetLevelIsNotNull() {
            addCriterion("target_level is not null");
            return (Criteria) this;
        }

        public Criteria andTargetLevelEqualTo(Byte value) {
            addCriterion("target_level =", value, "targetLevel");
            return (Criteria) this;
        }

        public Criteria andTargetLevelNotEqualTo(Byte value) {
            addCriterion("target_level <>", value, "targetLevel");
            return (Criteria) this;
        }

        public Criteria andTargetLevelGreaterThan(Byte value) {
            addCriterion("target_level >", value, "targetLevel");
            return (Criteria) this;
        }

        public Criteria andTargetLevelGreaterThanOrEqualTo(Byte value) {
            addCriterion("target_level >=", value, "targetLevel");
            return (Criteria) this;
        }

        public Criteria andTargetLevelLessThan(Byte value) {
            addCriterion("target_level <", value, "targetLevel");
            return (Criteria) this;
        }

        public Criteria andTargetLevelLessThanOrEqualTo(Byte value) {
            addCriterion("target_level <=", value, "targetLevel");
            return (Criteria) this;
        }

        public Criteria andTargetLevelIn(List<Byte> values) {
            addCriterion("target_level in", values, "targetLevel");
            return (Criteria) this;
        }

        public Criteria andTargetLevelNotIn(List<Byte> values) {
            addCriterion("target_level not in", values, "targetLevel");
            return (Criteria) this;
        }

        public Criteria andTargetLevelBetween(Byte value1, Byte value2) {
            addCriterion("target_level between", value1, value2, "targetLevel");
            return (Criteria) this;
        }

        public Criteria andTargetLevelNotBetween(Byte value1, Byte value2) {
            addCriterion("target_level not between", value1, value2, "targetLevel");
            return (Criteria) this;
        }

        public Criteria andTargetIdIsNull() {
            addCriterion("target_id is null");
            return (Criteria) this;
        }

        public Criteria andTargetIdIsNotNull() {
            addCriterion("target_id is not null");
            return (Criteria) this;
        }

        public Criteria andTargetIdEqualTo(Integer value) {
            addCriterion("target_id =", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdNotEqualTo(Integer value) {
            addCriterion("target_id <>", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdGreaterThan(Integer value) {
            addCriterion("target_id >", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("target_id >=", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdLessThan(Integer value) {
            addCriterion("target_id <", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdLessThanOrEqualTo(Integer value) {
            addCriterion("target_id <=", value, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdIn(List<Integer> values) {
            addCriterion("target_id in", values, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdNotIn(List<Integer> values) {
            addCriterion("target_id not in", values, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdBetween(Integer value1, Integer value2) {
            addCriterion("target_id between", value1, value2, "targetId");
            return (Criteria) this;
        }

        public Criteria andTargetIdNotBetween(Integer value1, Integer value2) {
            addCriterion("target_id not between", value1, value2, "targetId");
            return (Criteria) this;
        }

        public Criteria andMonitorKeyIsNull() {
            addCriterion("monitor_key is null");
            return (Criteria) this;
        }

        public Criteria andMonitorKeyIsNotNull() {
            addCriterion("monitor_key is not null");
            return (Criteria) this;
        }

        public Criteria andMonitorKeyEqualTo(String value) {
            addCriterion("monitor_key =", value, "monitorKey");
            return (Criteria) this;
        }

        public Criteria andMonitorKeyNotEqualTo(String value) {
            addCriterion("monitor_key <>", value, "monitorKey");
            return (Criteria) this;
        }

        public Criteria andMonitorKeyGreaterThan(String value) {
            addCriterion("monitor_key >", value, "monitorKey");
            return (Criteria) this;
        }

        public Criteria andMonitorKeyGreaterThanOrEqualTo(String value) {
            addCriterion("monitor_key >=", value, "monitorKey");
            return (Criteria) this;
        }

        public Criteria andMonitorKeyLessThan(String value) {
            addCriterion("monitor_key <", value, "monitorKey");
            return (Criteria) this;
        }

        public Criteria andMonitorKeyLessThanOrEqualTo(String value) {
            addCriterion("monitor_key <=", value, "monitorKey");
            return (Criteria) this;
        }

        public Criteria andMonitorKeyLike(String value) {
            addCriterion("monitor_key like", value, "monitorKey");
            return (Criteria) this;
        }

        public Criteria andMonitorKeyNotLike(String value) {
            addCriterion("monitor_key not like", value, "monitorKey");
            return (Criteria) this;
        }

        public Criteria andMonitorKeyIn(List<String> values) {
            addCriterion("monitor_key in", values, "monitorKey");
            return (Criteria) this;
        }

        public Criteria andMonitorKeyNotIn(List<String> values) {
            addCriterion("monitor_key not in", values, "monitorKey");
            return (Criteria) this;
        }

        public Criteria andMonitorKeyBetween(String value1, String value2) {
            addCriterion("monitor_key between", value1, value2, "monitorKey");
            return (Criteria) this;
        }

        public Criteria andMonitorKeyNotBetween(String value1, String value2) {
            addCriterion("monitor_key not between", value1, value2, "monitorKey");
            return (Criteria) this;
        }

        public Criteria andMonitorValueIsNull() {
            addCriterion("monitor_value is null");
            return (Criteria) this;
        }

        public Criteria andMonitorValueIsNotNull() {
            addCriterion("monitor_value is not null");
            return (Criteria) this;
        }

        public Criteria andMonitorValueEqualTo(Integer value) {
            addCriterion("monitor_value =", value, "monitorValue");
            return (Criteria) this;
        }

        public Criteria andMonitorValueNotEqualTo(Integer value) {
            addCriterion("monitor_value <>", value, "monitorValue");
            return (Criteria) this;
        }

        public Criteria andMonitorValueGreaterThan(Integer value) {
            addCriterion("monitor_value >", value, "monitorValue");
            return (Criteria) this;
        }

        public Criteria andMonitorValueGreaterThanOrEqualTo(Integer value) {
            addCriterion("monitor_value >=", value, "monitorValue");
            return (Criteria) this;
        }

        public Criteria andMonitorValueLessThan(Integer value) {
            addCriterion("monitor_value <", value, "monitorValue");
            return (Criteria) this;
        }

        public Criteria andMonitorValueLessThanOrEqualTo(Integer value) {
            addCriterion("monitor_value <=", value, "monitorValue");
            return (Criteria) this;
        }

        public Criteria andMonitorValueIn(List<Integer> values) {
            addCriterion("monitor_value in", values, "monitorValue");
            return (Criteria) this;
        }

        public Criteria andMonitorValueNotIn(List<Integer> values) {
            addCriterion("monitor_value not in", values, "monitorValue");
            return (Criteria) this;
        }

        public Criteria andMonitorValueBetween(Integer value1, Integer value2) {
            addCriterion("monitor_value between", value1, value2, "monitorValue");
            return (Criteria) this;
        }

        public Criteria andMonitorValueNotBetween(Integer value1, Integer value2) {
            addCriterion("monitor_value not between", value1, value2, "monitorValue");
            return (Criteria) this;
        }

        public Criteria andIsRealtimeIsNull() {
            addCriterion("is_realtime is null");
            return (Criteria) this;
        }

        public Criteria andIsRealtimeIsNotNull() {
            addCriterion("is_realtime is not null");
            return (Criteria) this;
        }

        public Criteria andIsRealtimeEqualTo(Byte value) {
            addCriterion("is_realtime =", value, "isRealtime");
            return (Criteria) this;
        }

        public Criteria andIsRealtimeNotEqualTo(Byte value) {
            addCriterion("is_realtime <>", value, "isRealtime");
            return (Criteria) this;
        }

        public Criteria andIsRealtimeGreaterThan(Byte value) {
            addCriterion("is_realtime >", value, "isRealtime");
            return (Criteria) this;
        }

        public Criteria andIsRealtimeGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_realtime >=", value, "isRealtime");
            return (Criteria) this;
        }

        public Criteria andIsRealtimeLessThan(Byte value) {
            addCriterion("is_realtime <", value, "isRealtime");
            return (Criteria) this;
        }

        public Criteria andIsRealtimeLessThanOrEqualTo(Byte value) {
            addCriterion("is_realtime <=", value, "isRealtime");
            return (Criteria) this;
        }

        public Criteria andIsRealtimeIn(List<Byte> values) {
            addCriterion("is_realtime in", values, "isRealtime");
            return (Criteria) this;
        }

        public Criteria andIsRealtimeNotIn(List<Byte> values) {
            addCriterion("is_realtime not in", values, "isRealtime");
            return (Criteria) this;
        }

        public Criteria andIsRealtimeBetween(Byte value1, Byte value2) {
            addCriterion("is_realtime between", value1, value2, "isRealtime");
            return (Criteria) this;
        }

        public Criteria andIsRealtimeNotBetween(Byte value1, Byte value2) {
            addCriterion("is_realtime not between", value1, value2, "isRealtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_work_status
     *
     * @mbggenerated do_not_delete_during_merge Mon May 21 10:13:05 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_work_status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}