package com.test.springboot.shiro.dao.entity;

import java.util.Date;

public class WorkorderHistoralEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_workorder_historal.id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_workorder_historal.create_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_workorder_historal.last_modify_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Date lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_workorder_historal.workorder_id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Integer workorderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_workorder_historal.user_id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_workorder_historal.operation
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Byte operation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_workorder_historal.operation_result
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Byte operationResult;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_workorder_historal.id
     *
     * @return the value of tb_workorder_historal.id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_workorder_historal.id
     *
     * @param id the value for tb_workorder_historal.id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_workorder_historal.create_time
     *
     * @return the value of tb_workorder_historal.create_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_workorder_historal.create_time
     *
     * @param createTime the value for tb_workorder_historal.create_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_workorder_historal.last_modify_time
     *
     * @return the value of tb_workorder_historal.last_modify_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_workorder_historal.last_modify_time
     *
     * @param lastModifyTime the value for tb_workorder_historal.last_modify_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_workorder_historal.workorder_id
     *
     * @return the value of tb_workorder_historal.workorder_id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Integer getWorkorderId() {
        return workorderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_workorder_historal.workorder_id
     *
     * @param workorderId the value for tb_workorder_historal.workorder_id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setWorkorderId(Integer workorderId) {
        this.workorderId = workorderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_workorder_historal.user_id
     *
     * @return the value of tb_workorder_historal.user_id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_workorder_historal.user_id
     *
     * @param userId the value for tb_workorder_historal.user_id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_workorder_historal.operation
     *
     * @return the value of tb_workorder_historal.operation
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Byte getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_workorder_historal.operation
     *
     * @param operation the value for tb_workorder_historal.operation
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setOperation(Byte operation) {
        this.operation = operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_workorder_historal.operation_result
     *
     * @return the value of tb_workorder_historal.operation_result
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Byte getOperationResult() {
        return operationResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_workorder_historal.operation_result
     *
     * @param operationResult the value for tb_workorder_historal.operation_result
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setOperationResult(Byte operationResult) {
        this.operationResult = operationResult;
    }
}