package com.test.springboot.shiro.dao.entity;

import java.util.Date;

public class WorkorderNotifyEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_workorder_notify.id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_workorder_notify.create_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_workorder_notify.last_modify_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Date lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_workorder_notify.workorder_id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Integer workorderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_workorder_notify.user_id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_workorder_notify.notify_content
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private String notifyContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_workorder_notify.notified
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Byte notified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_workorder_notify.notify_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    private Date notifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_workorder_notify.id
     *
     * @return the value of tb_workorder_notify.id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_workorder_notify.id
     *
     * @param id the value for tb_workorder_notify.id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_workorder_notify.create_time
     *
     * @return the value of tb_workorder_notify.create_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_workorder_notify.create_time
     *
     * @param createTime the value for tb_workorder_notify.create_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_workorder_notify.last_modify_time
     *
     * @return the value of tb_workorder_notify.last_modify_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_workorder_notify.last_modify_time
     *
     * @param lastModifyTime the value for tb_workorder_notify.last_modify_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_workorder_notify.workorder_id
     *
     * @return the value of tb_workorder_notify.workorder_id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Integer getWorkorderId() {
        return workorderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_workorder_notify.workorder_id
     *
     * @param workorderId the value for tb_workorder_notify.workorder_id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setWorkorderId(Integer workorderId) {
        this.workorderId = workorderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_workorder_notify.user_id
     *
     * @return the value of tb_workorder_notify.user_id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_workorder_notify.user_id
     *
     * @param userId the value for tb_workorder_notify.user_id
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_workorder_notify.notify_content
     *
     * @return the value of tb_workorder_notify.notify_content
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public String getNotifyContent() {
        return notifyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_workorder_notify.notify_content
     *
     * @param notifyContent the value for tb_workorder_notify.notify_content
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setNotifyContent(String notifyContent) {
        this.notifyContent = notifyContent == null ? null : notifyContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_workorder_notify.notified
     *
     * @return the value of tb_workorder_notify.notified
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Byte getNotified() {
        return notified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_workorder_notify.notified
     *
     * @param notified the value for tb_workorder_notify.notified
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setNotified(Byte notified) {
        this.notified = notified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_workorder_notify.notify_time
     *
     * @return the value of tb_workorder_notify.notify_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public Date getNotifyTime() {
        return notifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_workorder_notify.notify_time
     *
     * @param notifyTime the value for tb_workorder_notify.notify_time
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    public void setNotifyTime(Date notifyTime) {
        this.notifyTime = notifyTime;
    }
}