package com.test.springboot.shiro.dao.entity.mapper;

import com.test.springboot.shiro.dao.entity.AlarmHistoralEntity;
import com.test.springboot.shiro.dao.entity.AlarmHistoralEntityExample;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface AlarmHistoralEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_alarm_historal
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int countByExample(AlarmHistoralEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_alarm_historal
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int deleteByExample(AlarmHistoralEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_alarm_historal
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Delete({
        "delete from tb_alarm_historal",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_alarm_historal
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Insert({
        "insert into tb_alarm_historal (create_time, last_modify_time, ",
        "device_id, definition_id, ",
        "notify_status, device_name, ",
        "workshop_name, product_line_name)",
        "values (#{createTime,jdbcType=TIMESTAMP}, #{lastModifyTime,jdbcType=TIMESTAMP}, ",
        "#{deviceId,jdbcType=INTEGER}, #{definitionId,jdbcType=INTEGER}, ",
        "#{notifyStatus,jdbcType=TINYINT}, #{deviceName,jdbcType=VARCHAR}, ",
        "#{workshopName,jdbcType=VARCHAR}, #{productLineName,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(AlarmHistoralEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_alarm_historal
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int insertSelective(AlarmHistoralEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_alarm_historal
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    List<AlarmHistoralEntity> selectByExample(AlarmHistoralEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_alarm_historal
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Select({
        "select",
        "id, create_time, last_modify_time, device_id, definition_id, notify_status, ",
        "device_name, workshop_name, product_line_name",
        "from tb_alarm_historal",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    AlarmHistoralEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_alarm_historal
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") AlarmHistoralEntity record, @Param("example") AlarmHistoralEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_alarm_historal
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int updateByExample(@Param("record") AlarmHistoralEntity record, @Param("example") AlarmHistoralEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_alarm_historal
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int updateByPrimaryKeySelective(AlarmHistoralEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_alarm_historal
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Update({
        "update tb_alarm_historal",
        "set create_time = #{createTime,jdbcType=TIMESTAMP},",
          "last_modify_time = #{lastModifyTime,jdbcType=TIMESTAMP},",
          "device_id = #{deviceId,jdbcType=INTEGER},",
          "definition_id = #{definitionId,jdbcType=INTEGER},",
          "notify_status = #{notifyStatus,jdbcType=TINYINT},",
          "device_name = #{deviceName,jdbcType=VARCHAR},",
          "workshop_name = #{workshopName,jdbcType=VARCHAR},",
          "product_line_name = #{productLineName,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(AlarmHistoralEntity record);
}