package com.test.springboot.shiro.dao.entity.mapper;

import com.test.springboot.shiro.dao.entity.DeviceEntity;
import com.test.springboot.shiro.dao.entity.DeviceEntityExample;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface DeviceEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_device
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int countByExample(DeviceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_device
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int deleteByExample(DeviceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_device
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Delete({
        "delete from tb_device",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_device
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Insert({
        "insert into tb_device (name, device_type, ",
        "device_id, physics_number, ",
        "desc_info, manufacturer, ",
        "create_user_id, create_time, ",
        "last_modify_time, status, ",
        "person_liable_id, product_line_id, ",
        "order)",
        "values (#{name,jdbcType=VARCHAR}, #{deviceType,jdbcType=TINYINT}, ",
        "#{deviceId,jdbcType=VARCHAR}, #{physicsNumber,jdbcType=VARCHAR}, ",
        "#{descInfo,jdbcType=VARCHAR}, #{manufacturer,jdbcType=VARCHAR}, ",
        "#{createUserId,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{lastModifyTime,jdbcType=TIMESTAMP}, #{status,jdbcType=TINYINT}, ",
        "#{personLiableId,jdbcType=INTEGER}, #{productLineId,jdbcType=INTEGER}, ",
        "#{order,jdbcType=TINYINT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(DeviceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_device
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int insertSelective(DeviceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_device
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    List<DeviceEntity> selectByExample(DeviceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_device
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Select({
        "select",
        "id, name, device_type, device_id, physics_number, desc_info, manufacturer, create_user_id, ",
        "create_time, last_modify_time, status, person_liable_id, product_line_id, order",
        "from tb_device",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    DeviceEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_device
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") DeviceEntity record, @Param("example") DeviceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_device
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int updateByExample(@Param("record") DeviceEntity record, @Param("example") DeviceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_device
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int updateByPrimaryKeySelective(DeviceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_device
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Update({
        "update tb_device",
        "set name = #{name,jdbcType=VARCHAR},",
          "device_type = #{deviceType,jdbcType=TINYINT},",
          "device_id = #{deviceId,jdbcType=VARCHAR},",
          "physics_number = #{physicsNumber,jdbcType=VARCHAR},",
          "desc_info = #{descInfo,jdbcType=VARCHAR},",
          "manufacturer = #{manufacturer,jdbcType=VARCHAR},",
          "create_user_id = #{createUserId,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "last_modify_time = #{lastModifyTime,jdbcType=TIMESTAMP},",
          "status = #{status,jdbcType=TINYINT},",
          "person_liable_id = #{personLiableId,jdbcType=INTEGER},",
          "product_line_id = #{productLineId,jdbcType=INTEGER},",
          "order = #{order,jdbcType=TINYINT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(DeviceEntity record);
}