package com.test.springboot.shiro.dao.entity.mapper;

import com.test.springboot.shiro.dao.entity.GlobalSettingEntity;
import com.test.springboot.shiro.dao.entity.GlobalSettingEntityExample;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface GlobalSettingEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_global_setting
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int countByExample(GlobalSettingEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_global_setting
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int deleteByExample(GlobalSettingEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_global_setting
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Delete({
        "delete from tb_global_setting",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_global_setting
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Insert({
        "insert into tb_global_setting (setting_key, setting_value, ",
        "create_time, last_modify_time, ",
        "status)",
        "values (#{settingKey,jdbcType=VARCHAR}, #{settingValue,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{lastModifyTime,jdbcType=TIMESTAMP}, ",
        "#{status,jdbcType=TINYINT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(GlobalSettingEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_global_setting
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int insertSelective(GlobalSettingEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_global_setting
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    List<GlobalSettingEntity> selectByExample(GlobalSettingEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_global_setting
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Select({
        "select",
        "id, setting_key, setting_value, create_time, last_modify_time, status",
        "from tb_global_setting",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    GlobalSettingEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_global_setting
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") GlobalSettingEntity record, @Param("example") GlobalSettingEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_global_setting
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int updateByExample(@Param("record") GlobalSettingEntity record, @Param("example") GlobalSettingEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_global_setting
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int updateByPrimaryKeySelective(GlobalSettingEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_global_setting
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Update({
        "update tb_global_setting",
        "set setting_key = #{settingKey,jdbcType=VARCHAR},",
          "setting_value = #{settingValue,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "last_modify_time = #{lastModifyTime,jdbcType=TIMESTAMP},",
          "status = #{status,jdbcType=TINYINT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(GlobalSettingEntity record);
}