package com.test.springboot.shiro.dao.entity.mapper;

import com.test.springboot.shiro.dao.entity.MalfunctionDefinitionEntity;
import com.test.springboot.shiro.dao.entity.MalfunctionDefinitionEntityExample;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface MalfunctionDefinitionEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_malfunction_definition
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int countByExample(MalfunctionDefinitionEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_malfunction_definition
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int deleteByExample(MalfunctionDefinitionEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_malfunction_definition
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Delete({
        "delete from tb_malfunction_definition",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_malfunction_definition
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Insert({
        "insert into tb_malfunction_definition (create_time, last_modify_time, ",
        "type, display_name, ",
        "device_type, desc_info)",
        "values (#{createTime,jdbcType=TIMESTAMP}, #{lastModifyTime,jdbcType=TIMESTAMP}, ",
        "#{type,jdbcType=VARCHAR}, #{displayName,jdbcType=VARCHAR}, ",
        "#{deviceType,jdbcType=VARCHAR}, #{descInfo,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(MalfunctionDefinitionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_malfunction_definition
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int insertSelective(MalfunctionDefinitionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_malfunction_definition
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    List<MalfunctionDefinitionEntity> selectByExample(MalfunctionDefinitionEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_malfunction_definition
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Select({
        "select",
        "id, create_time, last_modify_time, type, display_name, device_type, desc_info",
        "from tb_malfunction_definition",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    MalfunctionDefinitionEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_malfunction_definition
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") MalfunctionDefinitionEntity record, @Param("example") MalfunctionDefinitionEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_malfunction_definition
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int updateByExample(@Param("record") MalfunctionDefinitionEntity record, @Param("example") MalfunctionDefinitionEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_malfunction_definition
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int updateByPrimaryKeySelective(MalfunctionDefinitionEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_malfunction_definition
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Update({
        "update tb_malfunction_definition",
        "set create_time = #{createTime,jdbcType=TIMESTAMP},",
          "last_modify_time = #{lastModifyTime,jdbcType=TIMESTAMP},",
          "type = #{type,jdbcType=VARCHAR},",
          "display_name = #{displayName,jdbcType=VARCHAR},",
          "device_type = #{deviceType,jdbcType=VARCHAR},",
          "desc_info = #{descInfo,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(MalfunctionDefinitionEntity record);
}