package com.test.springboot.shiro.dao.entity.mapper;

import com.test.springboot.shiro.dao.entity.ResourceOperationEntity;
import com.test.springboot.shiro.dao.entity.ResourceOperationEntityExample;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface ResourceOperationEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_resource_operation
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    int countByExample(ResourceOperationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_resource_operation
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    int deleteByExample(ResourceOperationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_resource_operation
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    @Delete({
        "delete from tb_resource_operation",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_resource_operation
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    @Insert({
        "insert into tb_resource_operation (resource_type_view, resource_type, ",
        "operation_type, permission, ",
        "api_status, create_time, ",
        "last_modify_time)",
        "values (#{resourceTypeView,jdbcType=VARCHAR}, #{resourceType,jdbcType=VARCHAR}, ",
        "#{operationType,jdbcType=VARCHAR}, #{permission,jdbcType=VARCHAR}, ",
        "#{apiStatus,jdbcType=TINYINT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{lastModifyTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(ResourceOperationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_resource_operation
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    int insertSelective(ResourceOperationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_resource_operation
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    List<ResourceOperationEntity> selectByExample(ResourceOperationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_resource_operation
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    @Select({
        "select",
        "id, resource_type_view, resource_type, operation_type, permission, api_status, ",
        "create_time, last_modify_time",
        "from tb_resource_operation",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    ResourceOperationEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_resource_operation
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") ResourceOperationEntity record, @Param("example") ResourceOperationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_resource_operation
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    int updateByExample(@Param("record") ResourceOperationEntity record, @Param("example") ResourceOperationEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_resource_operation
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    int updateByPrimaryKeySelective(ResourceOperationEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_resource_operation
     *
     * @mbggenerated Thu May 24 16:10:30 CST 2018
     */
    @Update({
        "update tb_resource_operation",
        "set resource_type_view = #{resourceTypeView,jdbcType=VARCHAR},",
          "resource_type = #{resourceType,jdbcType=VARCHAR},",
          "operation_type = #{operationType,jdbcType=VARCHAR},",
          "permission = #{permission,jdbcType=VARCHAR},",
          "api_status = #{apiStatus,jdbcType=TINYINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "last_modify_time = #{lastModifyTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ResourceOperationEntity record);
}