package com.test.springboot.shiro.dao.entity.mapper;

import com.test.springboot.shiro.dao.entity.RoleEntity;
import com.test.springboot.shiro.dao.entity.RoleEntityExample;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface RoleEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbggenerated Mon May 21 17:39:28 CST 2018
     */
    int countByExample(RoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbggenerated Mon May 21 17:39:28 CST 2018
     */
    int deleteByExample(RoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbggenerated Mon May 21 17:39:28 CST 2018
     */
    @Delete({
        "delete from tb_role",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbggenerated Mon May 21 17:39:28 CST 2018
     */
    @Insert({
        "insert into tb_role (access_menu_ids, access_resource_operation_ids, ",
        "create_time, role_name, ",
        "role_desc, last_modify_time)",
        "values (#{accessMenuIds,jdbcType=VARCHAR}, #{accessResourceOperationIds,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{roleName,jdbcType=VARCHAR}, ",
        "#{roleDesc,jdbcType=VARCHAR}, #{lastModifyTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(RoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbggenerated Mon May 21 17:39:28 CST 2018
     */
    int insertSelective(RoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbggenerated Mon May 21 17:39:28 CST 2018
     */
    List<RoleEntity> selectByExample(RoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbggenerated Mon May 21 17:39:28 CST 2018
     */
    @Select({
        "select",
        "id, access_menu_ids, access_resource_operation_ids, create_time, role_name, ",
        "role_desc, last_modify_time",
        "from tb_role",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    RoleEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbggenerated Mon May 21 17:39:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") RoleEntity record, @Param("example") RoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbggenerated Mon May 21 17:39:28 CST 2018
     */
    int updateByExample(@Param("record") RoleEntity record, @Param("example") RoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbggenerated Mon May 21 17:39:28 CST 2018
     */
    int updateByPrimaryKeySelective(RoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbggenerated Mon May 21 17:39:28 CST 2018
     */
    @Update({
        "update tb_role",
        "set access_menu_ids = #{accessMenuIds,jdbcType=VARCHAR},",
          "access_resource_operation_ids = #{accessResourceOperationIds,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "role_name = #{roleName,jdbcType=VARCHAR},",
          "role_desc = #{roleDesc,jdbcType=VARCHAR},",
          "last_modify_time = #{lastModifyTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(RoleEntity record);
}