package com.test.springboot.shiro.dao.entity.mapper;

import com.test.springboot.shiro.dao.entity.UserLogEntity;
import com.test.springboot.shiro.dao.entity.UserLogEntityExample;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface UserLogEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_log
     *
     * @mbggenerated Mon May 21 11:11:19 CST 2018
     */
    int countByExample(UserLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_log
     *
     * @mbggenerated Mon May 21 11:11:19 CST 2018
     */
    int deleteByExample(UserLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_log
     *
     * @mbggenerated Mon May 21 11:11:19 CST 2018
     */
    @Delete({
        "delete from tb_user_log",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_log
     *
     * @mbggenerated Mon May 21 11:11:19 CST 2018
     */
    @Insert({
        "insert into tb_user_log (user_id, create_time, ",
        "status, ip, content)",
        "values (#{userId,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{status,jdbcType=TINYINT}, #{ip,jdbcType=VARCHAR}, #{content,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(UserLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_log
     *
     * @mbggenerated Mon May 21 11:11:19 CST 2018
     */
    int insertSelective(UserLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_log
     *
     * @mbggenerated Mon May 21 11:11:19 CST 2018
     */
    List<UserLogEntity> selectByExample(UserLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_log
     *
     * @mbggenerated Mon May 21 11:11:19 CST 2018
     */
    @Select({
        "select",
        "id, user_id, create_time, status, ip, content",
        "from tb_user_log",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    UserLogEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_log
     *
     * @mbggenerated Mon May 21 11:11:19 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserLogEntity record, @Param("example") UserLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_log
     *
     * @mbggenerated Mon May 21 11:11:19 CST 2018
     */
    int updateByExample(@Param("record") UserLogEntity record, @Param("example") UserLogEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_log
     *
     * @mbggenerated Mon May 21 11:11:19 CST 2018
     */
    int updateByPrimaryKeySelective(UserLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_log
     *
     * @mbggenerated Mon May 21 11:11:19 CST 2018
     */
    @Update({
        "update tb_user_log",
        "set user_id = #{userId,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "status = #{status,jdbcType=TINYINT},",
          "ip = #{ip,jdbcType=VARCHAR},",
          "content = #{content,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(UserLogEntity record);
}