package com.test.springboot.shiro.dao.entity.mapper;

import com.test.springboot.shiro.dao.entity.ViewMenuEntity;
import com.test.springboot.shiro.dao.entity.ViewMenuEntityExample;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface ViewMenuEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_view_menu
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int countByExample(ViewMenuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_view_menu
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int deleteByExample(ViewMenuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_view_menu
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Delete({
        "delete from tb_view_menu",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_view_menu
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Insert({
        "insert into tb_view_menu (menu_name, parent_menu_id, ",
        "menu_label, create_time, ",
        "last_modify_time)",
        "values (#{menuName,jdbcType=VARCHAR}, #{parentMenuId,jdbcType=INTEGER}, ",
        "#{menuLabel,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{lastModifyTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(ViewMenuEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_view_menu
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int insertSelective(ViewMenuEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_view_menu
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    List<ViewMenuEntity> selectByExample(ViewMenuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_view_menu
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Select({
        "select",
        "id, menu_name, parent_menu_id, menu_label, create_time, last_modify_time",
        "from tb_view_menu",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    ViewMenuEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_view_menu
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") ViewMenuEntity record, @Param("example") ViewMenuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_view_menu
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int updateByExample(@Param("record") ViewMenuEntity record, @Param("example") ViewMenuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_view_menu
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int updateByPrimaryKeySelective(ViewMenuEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_view_menu
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Update({
        "update tb_view_menu",
        "set menu_name = #{menuName,jdbcType=VARCHAR},",
          "parent_menu_id = #{parentMenuId,jdbcType=INTEGER},",
          "menu_label = #{menuLabel,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "last_modify_time = #{lastModifyTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ViewMenuEntity record);
}