package com.test.springboot.shiro.dao.entity.mapper;

import com.test.springboot.shiro.dao.entity.WorkStatusEntity;
import com.test.springboot.shiro.dao.entity.WorkStatusEntityExample;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface WorkStatusEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_work_status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int countByExample(WorkStatusEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_work_status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int deleteByExample(WorkStatusEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_work_status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Delete({
        "delete from tb_work_status",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_work_status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Insert({
        "insert into tb_work_status (create_time, last_modify_time, ",
        "target_level, target_id, ",
        "monitor_key, monitor_value, ",
        "is_realtime)",
        "values (#{createTime,jdbcType=TIMESTAMP}, #{lastModifyTime,jdbcType=TIMESTAMP}, ",
        "#{targetLevel,jdbcType=TINYINT}, #{targetId,jdbcType=INTEGER}, ",
        "#{monitorKey,jdbcType=VARCHAR}, #{monitorValue,jdbcType=INTEGER}, ",
        "#{isRealtime,jdbcType=TINYINT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(WorkStatusEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_work_status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int insertSelective(WorkStatusEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_work_status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    List<WorkStatusEntity> selectByExample(WorkStatusEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_work_status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Select({
        "select",
        "id, create_time, last_modify_time, target_level, target_id, monitor_key, monitor_value, ",
        "is_realtime",
        "from tb_work_status",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    WorkStatusEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_work_status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") WorkStatusEntity record, @Param("example") WorkStatusEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_work_status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int updateByExample(@Param("record") WorkStatusEntity record, @Param("example") WorkStatusEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_work_status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int updateByPrimaryKeySelective(WorkStatusEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_work_status
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Update({
        "update tb_work_status",
        "set create_time = #{createTime,jdbcType=TIMESTAMP},",
          "last_modify_time = #{lastModifyTime,jdbcType=TIMESTAMP},",
          "target_level = #{targetLevel,jdbcType=TINYINT},",
          "target_id = #{targetId,jdbcType=INTEGER},",
          "monitor_key = #{monitorKey,jdbcType=VARCHAR},",
          "monitor_value = #{monitorValue,jdbcType=INTEGER},",
          "is_realtime = #{isRealtime,jdbcType=TINYINT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(WorkStatusEntity record);
}