package com.test.springboot.shiro.dao.entity.mapper;

import com.test.springboot.shiro.dao.entity.WorkshopEntity;
import com.test.springboot.shiro.dao.entity.WorkshopEntityExample;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface WorkshopEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_workshop
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int countByExample(WorkshopEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_workshop
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int deleteByExample(WorkshopEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_workshop
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Delete({
        "delete from tb_workshop",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_workshop
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Insert({
        "insert into tb_workshop (create_time, last_modify_time, ",
        "name, person_liable_id, ",
        "desc_info)",
        "values (#{createTime,jdbcType=TIMESTAMP}, #{lastModifyTime,jdbcType=TIMESTAMP}, ",
        "#{name,jdbcType=VARCHAR}, #{personLiableId,jdbcType=INTEGER}, ",
        "#{descInfo,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(WorkshopEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_workshop
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int insertSelective(WorkshopEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_workshop
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    List<WorkshopEntity> selectByExample(WorkshopEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_workshop
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Select({
        "select",
        "id, create_time, last_modify_time, name, person_liable_id, desc_info",
        "from tb_workshop",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    WorkshopEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_workshop
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") WorkshopEntity record, @Param("example") WorkshopEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_workshop
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int updateByExample(@Param("record") WorkshopEntity record, @Param("example") WorkshopEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_workshop
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int updateByPrimaryKeySelective(WorkshopEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_workshop
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Update({
        "update tb_workshop",
        "set create_time = #{createTime,jdbcType=TIMESTAMP},",
          "last_modify_time = #{lastModifyTime,jdbcType=TIMESTAMP},",
          "name = #{name,jdbcType=VARCHAR},",
          "person_liable_id = #{personLiableId,jdbcType=INTEGER},",
          "desc_info = #{descInfo,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(WorkshopEntity record);
}