package com.test.springboot.shiro.dao.entity.mapper;

import com.test.springboot.shiro.dao.entity.WorkorderEntity;
import com.test.springboot.shiro.dao.entity.WorkorderEntityExample;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface WorkorderEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_workorder
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int countByExample(WorkorderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_workorder
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int deleteByExample(WorkorderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_workorder
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Delete({
        "delete from tb_workorder",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_workorder
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Insert({
        "insert into tb_workorder (create_time, last_modify_time, ",
        "device_id, desc_info, ",
        "create_user, person_liable, ",
        "malfunction_id, reviewer, ",
        "status, owner)",
        "values (#{createTime,jdbcType=TIMESTAMP}, #{lastModifyTime,jdbcType=TIMESTAMP}, ",
        "#{deviceId,jdbcType=INTEGER}, #{descInfo,jdbcType=VARCHAR}, ",
        "#{createUser,jdbcType=VARCHAR}, #{personLiable,jdbcType=VARCHAR}, ",
        "#{malfunctionId,jdbcType=INTEGER}, #{reviewer,jdbcType=VARCHAR}, ",
        "#{status,jdbcType=TINYINT}, #{owner,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(WorkorderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_workorder
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int insertSelective(WorkorderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_workorder
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    List<WorkorderEntity> selectByExample(WorkorderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_workorder
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Select({
        "select",
        "id, create_time, last_modify_time, device_id, desc_info, create_user, person_liable, ",
        "malfunction_id, reviewer, status, owner",
        "from tb_workorder",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    WorkorderEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_workorder
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") WorkorderEntity record, @Param("example") WorkorderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_workorder
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int updateByExample(@Param("record") WorkorderEntity record, @Param("example") WorkorderEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_workorder
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int updateByPrimaryKeySelective(WorkorderEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_workorder
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Update({
        "update tb_workorder",
        "set create_time = #{createTime,jdbcType=TIMESTAMP},",
          "last_modify_time = #{lastModifyTime,jdbcType=TIMESTAMP},",
          "device_id = #{deviceId,jdbcType=INTEGER},",
          "desc_info = #{descInfo,jdbcType=VARCHAR},",
          "create_user = #{createUser,jdbcType=VARCHAR},",
          "person_liable = #{personLiable,jdbcType=VARCHAR},",
          "malfunction_id = #{malfunctionId,jdbcType=INTEGER},",
          "reviewer = #{reviewer,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=TINYINT},",
          "owner = #{owner,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(WorkorderEntity record);
}