package com.test.springboot.shiro.dao.entity.mapper;

import com.test.springboot.shiro.dao.entity.WorkorderNotifyEntity;
import com.test.springboot.shiro.dao.entity.WorkorderNotifyEntityExample;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface WorkorderNotifyEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_workorder_notify
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int countByExample(WorkorderNotifyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_workorder_notify
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int deleteByExample(WorkorderNotifyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_workorder_notify
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Delete({
        "delete from tb_workorder_notify",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_workorder_notify
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Insert({
        "insert into tb_workorder_notify (create_time, last_modify_time, ",
        "workorder_id, user_id, ",
        "notify_content, notified, ",
        "notify_time)",
        "values (#{createTime,jdbcType=TIMESTAMP}, #{lastModifyTime,jdbcType=TIMESTAMP}, ",
        "#{workorderId,jdbcType=INTEGER}, #{userId,jdbcType=INTEGER}, ",
        "#{notifyContent,jdbcType=VARCHAR}, #{notified,jdbcType=TINYINT}, ",
        "#{notifyTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(WorkorderNotifyEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_workorder_notify
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int insertSelective(WorkorderNotifyEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_workorder_notify
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    List<WorkorderNotifyEntity> selectByExample(WorkorderNotifyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_workorder_notify
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Select({
        "select",
        "id, create_time, last_modify_time, workorder_id, user_id, notify_content, notified, ",
        "notify_time",
        "from tb_workorder_notify",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    WorkorderNotifyEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_workorder_notify
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") WorkorderNotifyEntity record, @Param("example") WorkorderNotifyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_workorder_notify
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int updateByExample(@Param("record") WorkorderNotifyEntity record, @Param("example") WorkorderNotifyEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_workorder_notify
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    int updateByPrimaryKeySelective(WorkorderNotifyEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_workorder_notify
     *
     * @mbggenerated Mon May 21 10:13:05 CST 2018
     */
    @Update({
        "update tb_workorder_notify",
        "set create_time = #{createTime,jdbcType=TIMESTAMP},",
          "last_modify_time = #{lastModifyTime,jdbcType=TIMESTAMP},",
          "workorder_id = #{workorderId,jdbcType=INTEGER},",
          "user_id = #{userId,jdbcType=INTEGER},",
          "notify_content = #{notifyContent,jdbcType=VARCHAR},",
          "notified = #{notified,jdbcType=TINYINT},",
          "notify_time = #{notifyTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(WorkorderNotifyEntity record);
}